export const BedlamCards = [
{   message: "A gassy coworker",    quip: "When is it appropriate to ask a coworker if their gut flora is healthy?"},
{   message: "Strategery",    quip: "Stra - TEE - ger - ee"},
{   message: "Headhunting emails from recruiters",    quip: "Competition for talent in this industry is fierce"},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
{   message: "",    quip: ""},
];