import { Card, Rank, Suit } from "../Models/Card";

export const Cards = {
  AceClubs: new Card(Suit.Club, Rank.Ace),
  KingClubs: new Card(Suit.Club, Rank.King),
  QueenClubs: new Card(Suit.Club, Rank.Queen),
  JackClubs: new Card(Suit.Club, Rank.Jack),
  TenClubs: new Card(Suit.Club, Rank.Ten),
  NineClubs: new Card(Suit.Club, Rank.Nine),
  EightClubs: new Card(Suit.Club, Rank.Eight),
  SevenClubs: new Card(Suit.Club, Rank.Seven),
  SixClubs: new Card(Suit.Club, Rank.Six),
  FiveClubs: new Card(Suit.Club, Rank.Five),
  FourClubs: new Card(Suit.Club, Rank.Four),
  ThreeClubs: new Card(Suit.Club, Rank.Three),
  TwoClubs: new Card(Suit.Club, Rank.Two),

  AceDiamonds: new Card(Suit.Diamond, Rank.Ace),
  KingDiamonds: new Card(Suit.Diamond, Rank.King),
  QueenDiamonds: new Card(Suit.Diamond, Rank.Queen),
  JackDiamonds: new Card(Suit.Diamond, Rank.Jack),
  TenDiamonds: new Card(Suit.Diamond, Rank.Ten),
  NineDiamonds: new Card(Suit.Diamond, Rank.Nine),
  EightDiamonds: new Card(Suit.Diamond, Rank.Eight),
  SevenDiamonds: new Card(Suit.Diamond, Rank.Seven),
  SixDiamonds: new Card(Suit.Diamond, Rank.Six),
  FiveDiamonds: new Card(Suit.Diamond, Rank.Five),
  FourDiamonds: new Card(Suit.Diamond, Rank.Four),
  ThreeDiamonds: new Card(Suit.Diamond, Rank.Three),
  TwoDiamonds: new Card(Suit.Diamond, Rank.Two),

  AceHearts: new Card(Suit.Heart, Rank.Ace),
  KingHearts: new Card(Suit.Heart, Rank.King),
  QueenHearts: new Card(Suit.Heart, Rank.Queen),
  JackHearts: new Card(Suit.Heart, Rank.Jack),
  TenHearts: new Card(Suit.Heart, Rank.Ten),
  NineHearts: new Card(Suit.Heart, Rank.Nine),
  EightHearts: new Card(Suit.Heart, Rank.Eight),
  SevenHearts: new Card(Suit.Heart, Rank.Seven),
  SixHearts: new Card(Suit.Heart, Rank.Six),
  FiveHearts: new Card(Suit.Heart, Rank.Five),
  FourHearts: new Card(Suit.Heart, Rank.Four),
  ThreeHearts: new Card(Suit.Heart, Rank.Three),
  TwoHearts: new Card(Suit.Heart, Rank.Two),

  AceSpades: new Card(Suit.Spade, Rank.Ace),
  KingSpades: new Card(Suit.Spade, Rank.King),
  QueenSpades: new Card(Suit.Spade, Rank.Queen),
  JackSpades: new Card(Suit.Spade, Rank.Jack),
  TenSpades: new Card(Suit.Spade, Rank.Ten),
  NineSpades: new Card(Suit.Spade, Rank.Nine),
  EightSpades: new Card(Suit.Spade, Rank.Eight),
  SevenSpades: new Card(Suit.Spade, Rank.Seven),
  SixSpades: new Card(Suit.Spade, Rank.Six),
  FiveSpades: new Card(Suit.Spade, Rank.Five),
  FourSpades: new Card(Suit.Spade, Rank.Four),
  ThreeSpades: new Card(Suit.Spade, Rank.Three),
  TwoSpades: new Card(Suit.Spade, Rank.Two),
};
